defmodule StableMint.Repo.Migrations.CreateInitialResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transfers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idempotency_key, :text, null: false
      add :type, :text, null: false
      add :status, :text, default: "pending"
      add :amount, :decimal, null: false
      add :currency, :text, null: false
      add :source_type, :text
      add :source_id, :uuid
      add :destination_type, :text
      add :destination_id, :uuid
      add :chain_tx_hash, :text
      add :error_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :deployment_id, :uuid, null: false
    end

    create table(:stablecoins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :symbol, :text, null: false
      add :decimals, :bigint, default: 6
      add :status, :text, default: "active"
      add :total_supply, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stablecoins, [:symbol], name: "stablecoins_unique_symbol_index")

    create table(:ledger_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :entry_type, :text, null: false
      add :amount, :decimal, null: false
      add :currency, :text, null: false
      add :balance_after, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :transfer_id,
          references(:transfers,
            column: :id,
            name: "ledger_entries_transfer_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :account_id, :uuid, null: false
    end

    create table(:fiat_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :institution_name, :text, null: false
      add :account_type, :text, null: false
      add :routing_number, :text
      add :account_number_last4, :text
      add :status, :text, default: "verified"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id, :uuid, null: false
    end

    create table(:deployments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:transfers) do
      modify :deployment_id,
             references(:deployments,
               column: :id,
               name: "transfers_deployment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:transfers, [:idempotency_key],
             name: "transfers_unique_idempotency_key_index"
           )

    alter table(:deployments) do
      add :chain, :text, null: false
      add :contract_address, :text
      add :status, :text, default: "active"
      add :mint_enabled, :boolean, default: true
      add :burn_enabled, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :stablecoin_id,
          references(:stablecoins,
            column: :id,
            name: "deployments_stablecoin_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:deployments, [:stablecoin_id, :chain],
             name: "deployments_unique_chain_per_stablecoin_index"
           )

    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chain, :text, null: false
      add :address, :text, null: false
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id, :uuid, null: false
    end

    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ledger_entries) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "ledger_entries_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:fiat_accounts) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "fiat_accounts_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:addresses) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "addresses_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:addresses, [:chain, :address],
             name: "addresses_unique_address_per_chain_index"
           )

    alter table(:accounts) do
      add :name, :text, null: false
      add :type, :text, null: false
      add :status, :text, default: "active"
      add :custody_model, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:accounts) do
      remove :updated_at
      remove :inserted_at
      remove :custody_model
      remove :status
      remove :type
      remove :name
    end

    drop_if_exists unique_index(:addresses, [:chain, :address],
                     name: "addresses_unique_address_per_chain_index"
                   )

    drop constraint(:addresses, "addresses_account_id_fkey")

    alter table(:addresses) do
      modify :account_id, :uuid
    end

    drop constraint(:fiat_accounts, "fiat_accounts_account_id_fkey")

    alter table(:fiat_accounts) do
      modify :account_id, :uuid
    end

    drop constraint(:ledger_entries, "ledger_entries_account_id_fkey")

    alter table(:ledger_entries) do
      modify :account_id, :uuid
    end

    drop table(:accounts)

    drop table(:addresses)

    drop_if_exists unique_index(:deployments, [:stablecoin_id, :chain],
                     name: "deployments_unique_chain_per_stablecoin_index"
                   )

    drop constraint(:deployments, "deployments_stablecoin_id_fkey")

    alter table(:deployments) do
      remove :stablecoin_id
      remove :updated_at
      remove :inserted_at
      remove :burn_enabled
      remove :mint_enabled
      remove :status
      remove :contract_address
      remove :chain
    end

    drop_if_exists unique_index(:transfers, [:idempotency_key],
                     name: "transfers_unique_idempotency_key_index"
                   )

    drop constraint(:transfers, "transfers_deployment_id_fkey")

    alter table(:transfers) do
      modify :deployment_id, :uuid
    end

    drop table(:deployments)

    drop table(:fiat_accounts)

    drop constraint(:ledger_entries, "ledger_entries_transfer_id_fkey")

    drop table(:ledger_entries)

    drop_if_exists unique_index(:stablecoins, [:symbol], name: "stablecoins_unique_symbol_index")

    drop table(:stablecoins)

    drop table(:transfers)
  end
end
